/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerDetail: typeof import('./src/components/BannerDetail/BannerDetail.vue')['default']
    ContentArea: typeof import('./src/components/ContentArea/ContentArea.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LargerBanner: typeof import('./src/components/LargerBanner/LargerBanner.vue')['default']
    Lyric: typeof import('./src/components/Lyric/Lyric.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    Player: typeof import('./src/components/Player/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TrackList: typeof import('./src/components/TrackList/TrackList.vue')['default']
  }
}
